/**
 * GSAP Template Registry
 * Auto-generated by watch-gsap-templates.mjs
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

import { GSAPTemplateMetadata } from '@/types/gsap-template.types';

/**
 * Registry of available GSAP templates
 */
export const gsapTemplates: GSAPTemplateMetadata[] = [
  {
    id: "photo-exif",
    name: "Photo Exif",
    description: "A GSAP-based HTML template that displays photos with EXIF metadata using smooth animations.",
    category: "photo",
    thumbnail: "/gsap/photo-exif/thumbnail.png"
  }
];

/**
 * Get all GSAP templates
 */
export function getAllTemplates(): GSAPTemplateMetadata[] {
  return gsapTemplates;
}

/**
 * Get template by ID
 */
export function getTemplateById(id: string): GSAPTemplateMetadata | undefined {
  return gsapTemplates.find((t) => t.id === id);
}

/**
 * Get templates by category
 */
export function getTemplatesByCategory(
  category: GSAPTemplateMetadata['category']
): GSAPTemplateMetadata[] {
  return gsapTemplates.filter((t) => t.category === category);
}

/**
 * Search templates by name or description
 */
export function searchTemplates(query: string): GSAPTemplateMetadata[] {
  const lowerQuery = query.toLowerCase();
  return gsapTemplates.filter(
    (t) =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery)
  );
}
