services:
  # ─── Next.js app (API + web) ───────────────────────────────────────────────
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - redis
      - minio
    volumes:
      - ./prisma:/app/prisma
    environment:
      - REDIS_URL=${REDIS_URL}
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - APP_PORT=${APP_PORT}

  # ─── Redis for BullMQ queue ────────────────────────────────────────────────
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # ─── MinIO for S3-compatible storage ──────────────────────────────────────
  minio:
    image: minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    restart: unless-stopped
    ports:
      - "${S3_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER:     ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data:
