services:
  # ─── Next.js app (API + web) ───────────────────────────────────────────────
  app:
    build: .
    env_file: .env
#    platform: linux/amd64
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - redis
      - minio
    volumes:
      - ./prisma:/app/prisma
    environment:
      - REDIS_URL=${REDIS_URL}
      - WORKER_CONCURRENCY=2
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_CDN=${S3_CDN}

  # ─── Redis for BullMQ queue ────────────────────────────────────────────────
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # ─── MinIO for S3-compatible storage ──────────────────────────────────────
  minio:
    image: minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    restart: unless-stopped
    ports:
      - "${S3_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER:     ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio-data:/data

volumes:
  minio-data:
